about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("", include("posts.urls")),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

templates/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
        <!-- Загрузка статики -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
        <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
        <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    </head>
    <body>
        {% include 'nav.html' %}
        <main>
            <div class="container">
                {% block content %}
                <!-- Содержимое страницы -->
                {% endblock content %}
            </div>
        </main>
        {% include 'footer.html' %}

    </body>
</html>

templates/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
<div class="card my-4">
    <form method="post" action="{% url 'add_comment' post.author.username post.id %}">
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <div class="form-group">
                {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
    </form>
</div>
{% endif %}

<!-- Комментарии -->
{% for item in comments %}
<div class="media card mb-4">
    <div class="media-body card-body">
        <h5 class="mt-0">
            <a href="{% url 'profile' item.author.username %}"
               name="comment_{{ item.id }}">
                {{ item.author.username }}
            </a>
        </h5>
        <p>{{ item.text | linebreaksbr }}</p>
    </div>
</div>
{% endfor %}

templates/follow.html
{% extends "base.html" %} 
{% block title %} Посты авторов, на которых подписан {% endblock %}
{% block content %}
<div class="container">

    {% include "menu.html" with follow=True %}

        <h1>Последние обновления на сайте</h1>

        {% for post in page %}
            {% include "post_item.html" with post=post %}
        {% endfor %}

        {% if page.has_other_pages %}
            {% include "paginator.html" with items=page paginator=paginator %}
        {% endif %}

    </div>
{% endblock %}

templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <a href="{% url 'about:author' %}">Об авторе</a>
    <a href="{% url 'about:tech' %}">Технологии</a>
    <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube © {{year}}, все права защищены.</p>
</footer>

templates/group.html
{% extends "base.html" %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block header %}{{ group.title }}{% endblock %}
{% block content %}

    <h1>{{ group.title }}</h1>
    <p>{{ group.description|linebreaksbr }}</p>
    {% for post in page %}
                  <!-- Вот он, новый include! -->
                    {% include "post_item.html" with post=post %}
                {% endfor %}
    </div>

        <!-- Вывод паджинатора -->
        {% if page.has_other_pages %}
            {% include "paginator.html" with items=page paginator=paginator%}
        {% endif %}

{% endblock %}

templates/index.html
{% extends "base.html" %} 
{% block title %} Последние обновления {% endblock %}

{% block content %}
<div class="container">

    {% include "menu.html" with index=True %}
    
    {% load cache %}
    {% cache 20 sidebar index_page page.number %}
        <h1>Последние обновления на сайте</h1>

        {% for post in page %}
            {% include "post_item.html" with post=post %}
        {% endfor %}
    {% endcache %}

        {% if page.has_other_pages %}
            {% include "paginator.html" with items=page paginator=paginator %}
        {% endif %}

    </div>
{% endblock %} 

templates/menu.html
{% if user.is_authenticated %} 
<div class="row">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if index %}active{% endif %}" href="{% url 'index' %}">
                  Все авторы
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if follow %}active{% endif %}" href="/follow">
                Избранные авторы
            </a>
        </li>
    </ul>
</div>
{% endif %} 

templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url 'index' %}"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        Пользователь: {{ user.username }}
        <a class="p-2 text-dark" href="{% url 'profile' user.username %}">Профиль пользователя</a>
        <a class="p-2 text-dark" href="{% url 'new_post' %}">Создать новую запись</a>
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

templates/new.html
{% extends "base.html" %}
{% block title %}Новая запись{% endblock %}
{% block content %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">{% if post %}Редактирование записи{% else %}
                Создать новую запись{% endif %}
            </div>
            <div class="card-body">

                    {% for error in form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endfor %}


                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}'true'{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">
                                    {{ field }}
                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">              
                            <button type="submit" class="btn btn-primary">
                                {% if post %}Сохранить{% else %}
                                Добавить{% endif %}
                            </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %} 

templates/paginator.html
{# Отрисовываем навигацию паджинатора только если есть и другие страницы #}
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/post_item.html
<div class="card mb-3 mt-1 shadow-sm">

    <!-- Отображение картинки -->
    {% load thumbnail %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img" src="{{ im.url }}" />
    {% endthumbnail %}
    <!-- Отображение текста поста -->
    <div class="card-body">
      <p class="card-text">
        <!-- Ссылка на автора через @ -->
        <a name="post_{{ post.id }}" href="{% url 'profile' post.author.username %}">
          <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
        </a>
        {{ post.text|linebreaksbr }}
      </p>

      <!-- Если пост относится к какому-нибудь сообществу, то отобразим ссылку на него через # -->
      {% if post.group %}
      <a class="card-link muted" href="{% url 'group' post.group.slug %}">
        <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
      </a>
      {% endif %}
  
      <!-- Отображение ссылки на комментарии -->
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          {% if post.comments.exists %}
          <div>
            Комментариев: {{ post.comments.count }}
          </div>
          {% endif %}
          <a class="btn btn-sm btn-primary" href="{% url 'post' post.author.username post.id %}" role="button">
            Добавить комментарий
          </a>
  
          <!-- Ссылка на редактирование поста для автора -->
          {% if user == post.author %}
          <a class="btn btn-sm btn-info" href="{% url 'post_edit' post.author.username post.id %}" role="button">
            Редактировать
          </a>
          {% endif %}
        </div>
  
        <!-- Дата публикации поста -->
        <small class="text-muted">{{ post.pub_date }}</small>
      </div>
    </div>
  </div>